"""DXCC entity lookup from amateur radio callsign prefixes.

Uses an embedded prefix table covering ~200 DXCC entities.  Prefixes
are matched longest-first so ``VK9N`` matches Norfolk Island before
``VK`` matches Australia.
"""

import logging
import re
from dataclasses import dataclass

logger = logging.getLogger("elmer.callsign")


@dataclass
class DXCCEntity:
    entity_name: str
    prefix: str
    continent: str
    cq_zone: int
    itu_zone: int


# ---------------------------------------------------------------------------
# Prefix table — ordered entries, matched longest-first at lookup time.
# Covers major DXCC entities.  Format: (prefix, entity, continent, CQ, ITU)
# ---------------------------------------------------------------------------

_PREFIX_TABLE: list[tuple[str, str, str, int, int]] = [
    # North America
    ("K", "United States", "NA", 3, 7),
    ("W", "United States", "NA", 4, 8),
    ("N", "United States", "NA", 5, 8),
    ("AA", "United States", "NA", 4, 8),
    ("AB", "United States", "NA", 4, 8),
    ("AC", "United States", "NA", 4, 8),
    ("AD", "United States", "NA", 4, 8),
    ("AE", "United States", "NA", 4, 8),
    ("AF", "United States", "NA", 4, 8),
    ("AG", "United States", "NA", 4, 8),
    ("AI", "United States", "NA", 4, 8),
    ("AJ", "United States", "NA", 4, 8),
    ("AK", "United States", "NA", 4, 8),
    ("AL", "United States", "NA", 1, 1),
    ("KL", "Alaska", "NA", 1, 1),
    ("KL7", "Alaska", "NA", 1, 1),
    ("NL7", "Alaska", "NA", 1, 1),
    ("WL7", "Alaska", "NA", 1, 1),
    ("KH6", "Hawaii", "OC", 31, 61),
    ("WH6", "Hawaii", "OC", 31, 61),
    ("NH6", "Hawaii", "OC", 31, 61),
    ("KH2", "Guam", "OC", 27, 64),
    ("KH0", "Mariana Is.", "OC", 27, 64),
    ("KH8", "American Samoa", "OC", 32, 62),
    ("KP2", "US Virgin Is.", "NA", 8, 11),
    ("KP4", "Puerto Rico", "NA", 8, 11),
    ("KP1", "Navassa I.", "NA", 8, 11),
    ("VE", "Canada", "NA", 2, 4),
    ("VA", "Canada", "NA", 2, 4),
    ("VO", "Canada", "NA", 2, 4),
    ("VY", "Canada", "NA", 2, 3),
    ("CF", "Canada", "NA", 2, 4),
    ("CG", "Canada", "NA", 2, 4),
    ("CI", "Canada", "NA", 2, 4),
    ("CJ", "Canada", "NA", 2, 4),
    ("CK", "Canada", "NA", 2, 4),
    ("CY0", "Sable I.", "NA", 5, 9),
    ("CY9", "St. Paul I.", "NA", 5, 9),
    ("XE", "Mexico", "NA", 6, 10),
    ("XF4", "Revillagigedo", "NA", 6, 10),
    # Central America & Caribbean
    ("TI", "Costa Rica", "NA", 7, 11),
    ("HP", "Panama", "NA", 7, 11),
    ("HR", "Honduras", "NA", 7, 11),
    ("TG", "Guatemala", "NA", 7, 11),
    ("YS", "El Salvador", "NA", 7, 11),
    ("YN", "Nicaragua", "NA", 7, 11),
    ("V3", "Belize", "NA", 7, 11),
    ("HI", "Dominican Rep.", "NA", 8, 11),
    ("HH", "Haiti", "NA", 8, 11),
    ("6Y", "Jamaica", "NA", 8, 11),
    ("CO", "Cuba", "NA", 8, 11),
    ("CM", "Cuba", "NA", 8, 11),
    ("VP5", "Turks & Caicos", "NA", 8, 11),
    ("VP9", "Bermuda", "NA", 5, 11),
    ("C6", "Bahamas", "NA", 8, 11),
    ("8P", "Barbados", "NA", 8, 11),
    ("J3", "Grenada", "NA", 8, 11),
    ("J6", "St. Lucia", "NA", 8, 11),
    ("J7", "Dominica", "NA", 8, 11),
    ("J8", "St. Vincent", "NA", 8, 11),
    ("V2", "Antigua & Barbuda", "NA", 8, 11),
    ("V4", "St. Kitts & Nevis", "NA", 8, 11),
    ("VP2M", "Montserrat", "NA", 8, 11),
    ("VP2E", "Anguilla", "NA", 8, 11),
    ("VP2V", "British Virgin Is.", "NA", 8, 11),
    ("PJ2", "Curacao", "SA", 9, 11),
    ("PJ4", "Bonaire", "SA", 9, 11),
    ("PJ5", "Saba & St. Eustatius", "NA", 8, 11),
    ("PJ7", "Sint Maarten", "NA", 8, 11),
    ("FG", "Guadeloupe", "NA", 8, 11),
    ("FM", "Martinique", "NA", 8, 11),
    ("FJ", "St. Barthelemy", "NA", 8, 11),
    ("FS", "St. Martin", "NA", 8, 11),
    ("9Y", "Trinidad & Tobago", "SA", 9, 11),
    # South America
    ("PY", "Brazil", "SA", 11, 15),
    ("PP", "Brazil", "SA", 11, 15),
    ("PR", "Brazil", "SA", 11, 15),
    ("PS", "Brazil", "SA", 11, 15),
    ("PT", "Brazil", "SA", 11, 15),
    ("PU", "Brazil", "SA", 11, 15),
    ("PV", "Brazil", "SA", 11, 15),
    ("PW", "Brazil", "SA", 11, 15),
    ("PX", "Brazil", "SA", 11, 15),
    ("ZP", "Paraguay", "SA", 11, 14),
    ("LU", "Argentina", "SA", 13, 14),
    ("LO", "Argentina", "SA", 13, 14),
    ("CE", "Chile", "SA", 12, 14),
    ("CA", "Chile", "SA", 12, 14),
    ("CB", "Chile", "SA", 12, 14),
    ("CC", "Chile", "SA", 12, 14),
    ("CD", "Chile", "SA", 12, 14),
    ("CE0Y", "Easter I.", "SA", 12, 63),
    ("CE0X", "San Felix", "SA", 12, 14),
    ("CE0Z", "Juan Fernandez", "SA", 12, 14),
    ("HC", "Ecuador", "SA", 10, 12),
    ("HC8", "Galapagos Is.", "SA", 10, 12),
    ("OA", "Peru", "SA", 10, 12),
    ("CP", "Bolivia", "SA", 10, 14),
    ("HK", "Colombia", "SA", 9, 12),
    ("YV", "Venezuela", "SA", 9, 12),
    ("8R", "Guyana", "SA", 9, 12),
    ("PZ", "Suriname", "SA", 9, 12),
    ("FY", "French Guiana", "SA", 9, 12),
    ("CX", "Uruguay", "SA", 13, 14),
    ("ZD7", "St. Helena", "AF", 36, 66),
    ("VP8/F", "Falkland Is.", "SA", 13, 16),
    ("VP8", "Falkland Is.", "SA", 13, 16),
    # Europe
    ("G", "England", "EU", 14, 27),
    ("M", "England", "EU", 14, 27),
    ("2E", "England", "EU", 14, 27),
    ("GW", "Wales", "EU", 14, 27),
    ("MW", "Wales", "EU", 14, 27),
    ("GM", "Scotland", "EU", 14, 27),
    ("MM", "Scotland", "EU", 14, 27),
    ("GI", "Northern Ireland", "EU", 14, 27),
    ("MI", "Northern Ireland", "EU", 14, 27),
    ("GD", "Isle of Man", "EU", 14, 27),
    ("MD", "Isle of Man", "EU", 14, 27),
    ("GJ", "Jersey", "EU", 14, 27),
    ("MJ", "Jersey", "EU", 14, 27),
    ("GU", "Guernsey", "EU", 14, 27),
    ("MU", "Guernsey", "EU", 14, 27),
    ("F", "France", "EU", 14, 27),
    ("DL", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DA", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DB", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DC", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DD", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DE", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DF", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DG", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DH", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DI", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DJ", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DK", "Fed. Rep. of Germany", "EU", 14, 28),
    ("DO", "Fed. Rep. of Germany", "EU", 14, 28),
    ("I", "Italy", "EU", 15, 28),
    ("IK", "Italy", "EU", 15, 28),
    ("IZ", "Italy", "EU", 15, 28),
    ("IW", "Italy", "EU", 15, 28),
    ("IS", "Sardinia", "EU", 15, 28),
    ("IT9", "Sicily", "EU", 15, 28),
    ("EA", "Spain", "EU", 14, 37),
    ("EB", "Spain", "EU", 14, 37),
    ("EC", "Spain", "EU", 14, 37),
    ("EA6", "Balearic Is.", "EU", 14, 37),
    ("EA8", "Canary Is.", "AF", 33, 36),
    ("EA9", "Ceuta & Melilla", "AF", 33, 37),
    ("CT", "Portugal", "EU", 14, 37),
    ("CU", "Azores", "EU", 14, 36),
    ("CR", "Portugal", "EU", 14, 37),
    ("PA", "Netherlands", "EU", 14, 27),
    ("PB", "Netherlands", "EU", 14, 27),
    ("PC", "Netherlands", "EU", 14, 27),
    ("PD", "Netherlands", "EU", 14, 27),
    ("PE", "Netherlands", "EU", 14, 27),
    ("PF", "Netherlands", "EU", 14, 27),
    ("PG", "Netherlands", "EU", 14, 27),
    ("PH", "Netherlands", "EU", 14, 27),
    ("PI", "Netherlands", "EU", 14, 27),
    ("ON", "Belgium", "EU", 14, 27),
    ("OO", "Belgium", "EU", 14, 27),
    ("OR", "Belgium", "EU", 14, 27),
    ("OS", "Belgium", "EU", 14, 27),
    ("OT", "Belgium", "EU", 14, 27),
    ("LX", "Luxembourg", "EU", 14, 27),
    ("HB9", "Switzerland", "EU", 14, 28),
    ("HB", "Switzerland", "EU", 14, 28),
    ("HB0", "Liechtenstein", "EU", 14, 28),
    ("OE", "Austria", "EU", 15, 28),
    ("OK", "Czech Republic", "EU", 15, 28),
    ("OL", "Czech Republic", "EU", 15, 28),
    ("OM", "Slovak Republic", "EU", 15, 28),
    ("HA", "Hungary", "EU", 15, 28),
    ("HG", "Hungary", "EU", 15, 28),
    ("SP", "Poland", "EU", 15, 28),
    ("SQ", "Poland", "EU", 15, 28),
    ("SN", "Poland", "EU", 15, 28),
    ("3A", "Monaco", "EU", 14, 27),
    ("9A", "Croatia", "EU", 15, 28),
    ("S5", "Slovenia", "EU", 15, 28),
    ("E7", "Bosnia-Herzegovina", "EU", 15, 28),
    ("YU", "Serbia", "EU", 15, 28),
    ("Z3", "North Macedonia", "EU", 15, 28),
    ("ZA", "Albania", "EU", 15, 28),
    ("9H", "Malta", "EU", 15, 28),
    ("SV", "Greece", "EU", 20, 28),
    ("SW", "Greece", "EU", 20, 28),
    ("SX", "Greece", "EU", 20, 28),
    ("SV5", "Dodecanese", "EU", 20, 28),
    ("SV9", "Crete", "EU", 20, 28),
    ("SV/A", "Mount Athos", "EU", 20, 28),
    ("TA", "Turkey", "AS", 20, 39),
    ("TC", "Turkey", "AS", 20, 39),
    ("YO", "Romania", "EU", 20, 28),
    ("YP", "Romania", "EU", 20, 28),
    ("YQ", "Romania", "EU", 20, 28),
    ("YR", "Romania", "EU", 20, 28),
    ("LZ", "Bulgaria", "EU", 20, 28),
    ("SM", "Sweden", "EU", 14, 18),
    ("SA", "Sweden", "EU", 14, 18),
    ("SB", "Sweden", "EU", 14, 18),
    ("SC", "Sweden", "EU", 14, 18),
    ("SD", "Sweden", "EU", 14, 18),
    ("SE", "Sweden", "EU", 14, 18),
    ("SF", "Sweden", "EU", 14, 18),
    ("SG", "Sweden", "EU", 14, 18),
    ("SH", "Sweden", "EU", 14, 18),
    ("SI", "Sweden", "EU", 14, 18),
    ("SJ", "Sweden", "EU", 14, 18),
    ("SK", "Sweden", "EU", 14, 18),
    ("SL", "Sweden", "EU", 14, 18),
    ("LA", "Norway", "EU", 14, 18),
    ("LB", "Norway", "EU", 14, 18),
    ("LC", "Norway", "EU", 14, 18),
    ("JW", "Svalbard", "EU", 40, 18),
    ("JX", "Jan Mayen", "EU", 40, 18),
    ("OZ", "Denmark", "EU", 14, 18),
    ("OU", "Denmark", "EU", 14, 18),
    ("OX", "Greenland", "NA", 40, 5),
    ("OW", "Faroe Is.", "EU", 14, 18),
    ("TF", "Iceland", "EU", 40, 17),
    ("OH", "Finland", "EU", 18, 18),
    ("OF", "Finland", "EU", 18, 18),
    ("OG", "Finland", "EU", 18, 18),
    ("OI", "Finland", "EU", 18, 18),
    ("OH0", "Aland Is.", "EU", 18, 18),
    ("ES", "Estonia", "EU", 15, 29),
    ("YL", "Latvia", "EU", 15, 29),
    ("LY", "Lithuania", "EU", 15, 29),
    ("EI", "Ireland", "EU", 14, 27),
    ("EJ", "Ireland", "EU", 14, 27),
    ("4U1V", "ITU HQ", "EU", 14, 28),
    # Russia / CIS
    ("R", "Russian Federation", "EU", 16, 29),
    ("RA", "Russian Federation", "EU", 16, 29),
    ("UA", "Russian Federation", "EU", 16, 29),
    ("RV", "Russian Federation", "EU", 16, 29),
    ("RW", "Russian Federation", "EU", 16, 29),
    ("RX", "Russian Federation", "EU", 16, 29),
    ("RZ", "Russian Federation", "EU", 16, 29),
    ("UA0", "Asiatic Russia", "AS", 18, 30),
    ("UA9", "Asiatic Russia", "AS", 17, 30),
    ("RA0", "Asiatic Russia", "AS", 18, 30),
    ("RA9", "Asiatic Russia", "AS", 17, 30),
    ("R0", "Asiatic Russia", "AS", 18, 30),
    ("R9", "Asiatic Russia", "AS", 17, 30),
    ("UR", "Ukraine", "EU", 16, 29),
    ("US", "Ukraine", "EU", 16, 29),
    ("UT", "Ukraine", "EU", 16, 29),
    ("UX", "Ukraine", "EU", 16, 29),
    ("UY", "Ukraine", "EU", 16, 29),
    ("EU", "Belarus", "EU", 16, 29),
    ("EV", "Belarus", "EU", 16, 29),
    ("EW", "Belarus", "EU", 16, 29),
    ("ER", "Moldova", "EU", 16, 29),
    ("UN", "Kazakhstan", "AS", 17, 30),
    ("EX", "Kyrgyzstan", "AS", 17, 30),
    ("UJ", "Uzbekistan", "AS", 17, 30),
    ("EY", "Tajikistan", "AS", 17, 30),
    ("4J", "Azerbaijan", "AS", 21, 29),
    ("4L", "Georgia", "AS", 21, 29),
    ("EK", "Armenia", "AS", 21, 29),
    # Asia
    ("JA", "Japan", "AS", 25, 45),
    ("JE", "Japan", "AS", 25, 45),
    ("JF", "Japan", "AS", 25, 45),
    ("JG", "Japan", "AS", 25, 45),
    ("JH", "Japan", "AS", 25, 45),
    ("JI", "Japan", "AS", 25, 45),
    ("JJ", "Japan", "AS", 25, 45),
    ("JK", "Japan", "AS", 25, 45),
    ("JL", "Japan", "AS", 25, 45),
    ("JM", "Japan", "AS", 25, 45),
    ("JN", "Japan", "AS", 25, 45),
    ("JO", "Japan", "AS", 25, 45),
    ("JP", "Japan", "AS", 25, 45),
    ("JQ", "Japan", "AS", 25, 45),
    ("JR", "Japan", "AS", 25, 45),
    ("JS", "Japan", "AS", 25, 45),
    ("7J", "Japan", "AS", 25, 45),
    ("7K", "Japan", "AS", 25, 45),
    ("7L", "Japan", "AS", 25, 45),
    ("7M", "Japan", "AS", 25, 45),
    ("7N", "Japan", "AS", 25, 45),
    ("HL", "South Korea", "AS", 25, 44),
    ("DS", "South Korea", "AS", 25, 44),
    ("6K", "South Korea", "AS", 25, 44),
    ("BV", "Taiwan", "AS", 24, 44),
    ("BY", "China", "AS", 24, 44),
    ("BA", "China", "AS", 24, 44),
    ("BD", "China", "AS", 24, 44),
    ("BG", "China", "AS", 24, 44),
    ("BH", "China", "AS", 24, 44),
    ("BI", "China", "AS", 24, 44),
    ("BJ", "China", "AS", 24, 44),
    ("BL", "China", "AS", 24, 44),
    ("BM", "China", "AS", 24, 44),
    ("BN", "China", "AS", 24, 44),
    ("BO", "China", "AS", 24, 44),
    ("BP", "China", "AS", 24, 44),
    ("BQ", "China", "AS", 24, 44),
    ("BR", "China", "AS", 24, 44),
    ("BS", "China", "AS", 24, 44),
    ("BT", "China", "AS", 24, 44),
    ("BU", "China", "AS", 24, 44),
    ("BW", "China", "AS", 24, 44),
    ("BX", "China", "AS", 24, 44),
    ("VU", "India", "AS", 22, 41),
    ("4S", "Sri Lanka", "AS", 22, 41),
    ("AP", "Pakistan", "AS", 21, 40),
    ("9N", "Nepal", "AS", 22, 42),
    ("A5", "Bhutan", "AS", 22, 41),
    ("XW", "Laos", "AS", 26, 49),
    ("XU", "Cambodia", "AS", 26, 49),
    ("XV", "Vietnam", "AS", 26, 49),
    ("3W", "Vietnam", "AS", 26, 49),
    ("HS", "Thailand", "AS", 26, 49),
    ("E2", "Thailand", "AS", 26, 49),
    ("9M2", "West Malaysia", "AS", 28, 54),
    ("9M6", "East Malaysia", "OC", 28, 54),
    ("9V", "Singapore", "AS", 28, 54),
    ("YB", "Indonesia", "OC", 28, 54),
    ("DU", "Philippines", "OC", 27, 50),
    ("4F", "Philippines", "OC", 27, 50),
    ("A6", "United Arab Emirates", "AS", 21, 39),
    ("A7", "Qatar", "AS", 21, 39),
    ("A9", "Bahrain", "AS", 21, 39),
    ("9K", "Kuwait", "AS", 21, 39),
    ("HZ", "Saudi Arabia", "AS", 21, 39),
    ("7Z", "Saudi Arabia", "AS", 21, 39),
    ("OD", "Lebanon", "AS", 20, 39),
    ("4X", "Israel", "AS", 20, 39),
    ("4Z", "Israel", "AS", 20, 39),
    ("JY", "Jordan", "AS", 20, 39),
    ("YI", "Iraq", "AS", 21, 39),
    ("EP", "Iran", "AS", 21, 40),
    ("EQ", "Iran", "AS", 21, 40),
    ("YA", "Afghanistan", "AS", 21, 40),
    ("A4", "Oman", "AS", 21, 39),
    ("A2", "Botswana", "AF", 38, 57),
    ("A3", "Tonga", "OC", 32, 62),
    ("EZ", "Turkmenistan", "AS", 17, 30),
    # Oceania
    ("VK", "Australia", "OC", 30, 59),
    ("VK9N", "Norfolk I.", "OC", 32, 60),
    ("VK9X", "Christmas I.", "OC", 29, 54),
    ("VK9C", "Cocos-Keeling", "OC", 29, 54),
    ("VK9L", "Lord Howe I.", "OC", 30, 60),
    ("VK0M", "Macquarie I.", "OC", 30, 60),
    ("VK0H", "Heard I.", "AF", 39, 68),
    ("ZL", "New Zealand", "OC", 32, 60),
    ("ZM", "New Zealand", "OC", 32, 60),
    ("ZL7", "Chatham Is.", "OC", 32, 60),
    ("ZL8", "Kermadec Is.", "OC", 32, 60),
    ("ZL9", "Auckland & Campbell", "OC", 32, 60),
    ("FK", "New Caledonia", "OC", 32, 56),
    ("FO", "French Polynesia", "OC", 32, 63),
    ("FW", "Wallis & Futuna", "OC", 32, 62),
    ("KH1", "Baker & Howland", "OC", 31, 61),
    ("KH3", "Johnston I.", "OC", 31, 61),
    ("KH4", "Midway I.", "OC", 31, 61),
    ("KH5", "Palmyra & Jarvis", "OC", 31, 61),
    ("KH5K", "Kingman Reef", "OC", 31, 61),
    ("KH9", "Wake I.", "OC", 31, 65),
    ("T8", "Palau", "OC", 27, 64),
    ("V6", "Micronesia", "OC", 27, 65),
    ("V7", "Marshall Is.", "OC", 31, 65),
    ("T2", "Tuvalu", "OC", 31, 62),
    ("T3", "Kiribati", "OC", 31, 65),
    ("5W", "Samoa", "OC", 32, 62),
    ("ZK3", "Tokelau", "OC", 31, 62),
    ("E5", "Cook Is.", "OC", 32, 62),
    ("3D2", "Fiji", "OC", 32, 56),
    ("YJ", "Vanuatu", "OC", 32, 56),
    ("H4", "Solomon Is.", "OC", 28, 51),
    ("P2", "Papua New Guinea", "OC", 28, 51),
    # Africa
    ("ZS", "South Africa", "AF", 38, 57),
    ("ZR", "South Africa", "AF", 38, 57),
    ("ZT", "South Africa", "AF", 38, 57),
    ("ZU", "South Africa", "AF", 38, 57),
    ("V5", "Namibia", "AF", 38, 57),
    ("7P", "Lesotho", "AF", 38, 57),
    ("3DA", "Eswatini", "AF", 38, 57),
    ("A2", "Botswana", "AF", 38, 57),
    ("7Q", "Malawi", "AF", 37, 53),
    ("Z2", "Zimbabwe", "AF", 38, 53),
    ("9J", "Zambia", "AF", 36, 53),
    ("9I", "Zambia", "AF", 36, 53),
    ("5Z", "Kenya", "AF", 37, 48),
    ("5H", "Tanzania", "AF", 37, 53),
    ("5X", "Uganda", "AF", 37, 48),
    ("9U", "Burundi", "AF", 36, 52),
    ("9X", "Rwanda", "AF", 36, 52),
    ("ET", "Ethiopia", "AF", 37, 48),
    ("E3", "Eritrea", "AF", 37, 48),
    ("6O", "Somalia", "AF", 37, 48),
    ("T5", "Somalia", "AF", 37, 48),
    ("J2", "Djibouti", "AF", 37, 48),
    ("ST", "Sudan", "AF", 34, 47),
    ("SU", "Egypt", "AF", 34, 38),
    ("5A", "Libya", "AF", 34, 38),
    ("7X", "Algeria", "AF", 33, 37),
    ("CN", "Morocco", "AF", 33, 37),
    ("5T", "Mauritania", "AF", 35, 46),
    ("6W", "Senegal", "AF", 35, 46),
    ("C5", "Gambia", "AF", 35, 46),
    ("J5", "Guinea-Bissau", "AF", 35, 46),
    ("3X", "Guinea", "AF", 35, 46),
    ("EL", "Liberia", "AF", 35, 46),
    ("TU", "Cote d'Ivoire", "AF", 35, 46),
    ("XT", "Burkina Faso", "AF", 35, 46),
    ("5V", "Togo", "AF", 35, 46),
    ("TY", "Benin", "AF", 35, 46),
    ("5N", "Nigeria", "AF", 35, 46),
    ("TJ", "Cameroon", "AF", 36, 47),
    ("TN", "Republic of Congo", "AF", 36, 52),
    ("TT", "Chad", "AF", 36, 47),
    ("TR", "Gabon", "AF", 36, 52),
    ("TL", "Central African Rep.", "AF", 36, 47),
    ("9Q", "Dem. Rep. of Congo", "AF", 36, 52),
    ("D2", "Angola", "AF", 36, 52),
    ("C9", "Mozambique", "AF", 37, 53),
    ("5R", "Madagascar", "AF", 39, 53),
    ("FR", "Reunion", "AF", 39, 53),
    ("FH", "Mayotte", "AF", 39, 53),
    ("D6", "Comoros", "AF", 39, 53),
    ("S7", "Seychelles", "AF", 39, 53),
    ("3B8", "Mauritius", "AF", 39, 53),
    ("3B9", "Rodriguez I.", "AF", 39, 53),
    ("3B6", "Agalega & St. Brandon", "AF", 39, 53),
    ("VQ9", "Chagos Is.", "AF", 39, 41),
    ("ZD8", "Ascension I.", "AF", 36, 66),
    ("ZD9", "Tristan da Cunha", "AF", 38, 66),
    ("3C", "Equatorial Guinea", "AF", 36, 47),
    ("3C0", "Annobon I.", "AF", 36, 52),
    ("S0", "Western Sahara", "AF", 33, 46),
    # Antarctic
    ("DP0", "Antarctica", "AN", 13, 67),
    ("KC4", "Antarctica", "AN", 13, 67),
    ("RI1AN", "Antarctica", "AN", 13, 67),
    ("VP8/H", "South Shetland", "AN", 13, 73),
    ("VP8/O", "South Orkney", "AN", 13, 73),
    ("VP8/G", "South Georgia", "SA", 13, 73),
    ("VP8/S", "South Sandwich", "SA", 13, 73),
    # Rare / Most Wanted
    ("3Y", "Bouvet I.", "AF", 38, 67),
    ("FT5W", "Crozet I.", "AF", 39, 68),
    ("FT5X", "Kerguelen", "AF", 39, 68),
    ("FT5Z", "Amsterdam & St. Paul", "AF", 39, 68),
    ("P5", "North Korea", "AS", 25, 44),
    ("BS7", "Scarborough Reef", "AS", 26, 50),
    ("BV9P", "Pratas I.", "AS", 24, 44),
    ("KH7K", "Kure I.", "OC", 31, 61),
    ("SV2ASP/A", "Mount Athos", "EU", 20, 28),
    ("T3", "Kiribati", "OC", 31, 65),
    ("VU4", "Andaman & Nicobar", "AS", 26, 49),
    ("VU7", "Lakshadweep Is.", "AS", 22, 41),
    ("ZS8", "Prince Edward & Marion", "AF", 38, 57),
]


class CallsignLookup:
    """Look up DXCC entity from amateur radio callsign."""

    def __init__(self) -> None:
        # Build lookup sorted by prefix length (longest first).
        self._entries = sorted(
            _PREFIX_TABLE,
            key=lambda e: len(e[0]),
            reverse=True,
        )

    def get_entity(self, callsign: str) -> DXCCEntity | None:
        """Look up DXCC entity for a callsign."""
        if not callsign:
            return None

        call = callsign.upper().strip()

        # Handle portable indicators (e.g. W0ABE/P, DL/W0ABE, 3B8/OE6MBG).
        # Try each part; prefer the one with the longest prefix match,
        # which correctly identifies the operating entity.
        if "/" in call:
            parts = call.split("/")
            # Filter out common portable suffixes.
            _PORTABLE = {"P", "M", "MM", "AM", "QRP", "R", "LH"}
            candidates = [p for p in parts if p not in _PORTABLE and len(p) > 1]
            if not candidates:
                candidates = parts

            best: DXCCEntity | None = None
            best_prefix_len = -1
            for part in candidates:
                result = self._match_prefix(part)
                if result and len(result.prefix) > best_prefix_len:
                    best = result
                    best_prefix_len = len(result.prefix)
            return best

        return self._match_prefix(call)

    def _match_prefix(self, call: str) -> DXCCEntity | None:
        """Match a callsign against the prefix table (longest match wins)."""
        for prefix, entity, continent, cq, itu in self._entries:
            if call.startswith(prefix):
                return DXCCEntity(
                    entity_name=entity,
                    prefix=prefix,
                    continent=continent,
                    cq_zone=cq,
                    itu_zone=itu,
                )
        return None

    def get_prefix_info(self, prefix: str) -> DXCCEntity | None:
        """Look up entity by exact prefix."""
        p = prefix.upper().strip()
        for pfx, entity, continent, cq, itu in self._entries:
            if pfx == p:
                return DXCCEntity(
                    entity_name=entity,
                    prefix=pfx,
                    continent=continent,
                    cq_zone=cq,
                    itu_zone=itu,
                )
        return None


# Module-level singleton.
_lookup: CallsignLookup | None = None


def get_lookup() -> CallsignLookup:
    global _lookup
    if _lookup is None:
        _lookup = CallsignLookup()
    return _lookup
